name: Build and test

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v2

    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.2'
    
    - name: Verify Xcode Version
      run: xcodebuild -version
    
    - name: List available simulators
      run: xcrun simctl list devices available

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3

    - name: Install dependencies
      run: |
        bundle install
        cd FBSnapshotTestCaseDemo
        bundle exec pod install

    - name: Build and test
      run: |
        xcodebuild -workspace FBSnapshotTestCaseDemo.xcworkspace -scheme FBSnapshotTestCaseDemo -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6' build test | xcpretty -c && exit ${PIPESTATUS[0]}
